apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: dev-

images:
- name: aslahea/springboot-maven-app
  newTag: latest


commonLabels:
  environment: development
  managed-by: kustomize